version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

 
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - rabbitmq


  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"          # expose port 80 to host
    depends_on:
      - backend  

  worker:
    build: ./worker
    restart: always
    env_file:
      - ./worker/.env
    depends_on:
      - db
      - rabbitmq
    command: ["node","index.js"]

    
volumes:
  pgdata:
